apiVersion: v2 #
name: corndogs
description: A Helm chart for Kubernetes

type: application
version: 1.0.1
appVersion: "1.0.1"


dependencies:
  - name: postgresql
    version: ~10.13.8
    repository: https://charts.bitnami.com/bitnami/
    condition: postgresql.enabled
  - name: prometheus
    version: ~15.0.2
    repository: https://prometheus-community.github.io/helm-charts
    condition: appconfig.prometheusEnabled