apiVersion: v2
name: corndogs
description: A Helm chart for Kubernetes

type: application
version: 1.4.0
appVersion: "1.3.13"


dependencies:
  - name: postgresql
    version: ~12.1.6
    repository: https://charts.bitnami.com/bitnami/
    condition: postgresql.enabled
