apiVersion: v1
kind: Service
metadata:
  name: {{ include "corndogs.fullname" . }}
  labels:
    {{- include "corndogs.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: corndogsgrpc
      protocol: TCP
      name: corndogsgrpc
  selector:
    {{- include "corndogs.selectorLabels" . | nindent 4 }}
