name: Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  validate-pr-title:
    name: Validate PR Title
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v1
      - uses: amannn/action-semantic-pull-request@v3.4.6
        with:
          types: |
            fix
            feat
            norelease
        env:
          GITHUB_TOKEN: ${{ github.token }}
  lint-chart:
    if: ${{ !startsWith( github.head_ref, 'automated-code-release' ) }}
    name: Lint Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.2
      - run: |
          helm lint chart
  update-chart-dependencies:
    if: ${{ !startsWith( github.head_ref, 'automated-code-release' ) }}
    name: Update Chart Dependencies
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.2
      - run: |
          helm dependency update chart
  template-chart:
    if: ${{ !startsWith( github.head_ref, 'automated-code-release' ) }}
    name: Template Chart
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Helm
        uses: azure/setup-helm@v1
        with:
          version: v3.7.2
      - run: |
          helm template chart
  validate-branch:
    name: Validate branch
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Only allow alpha to be merged to main
        if: github.head_ref != 'alpha'
        run: |
          echo "Only alpha should be merged to main"
          exit 1
