name: Pull Request
on:
  pull_request:
    branches:
      - main
      - alpha
jobs:
  validate-pr-title:
    name: Validate PR Title
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v1
      - uses: amannn/action-semantic-pull-request@v3.4.6
        with:
          types: |
            fix
            feat
            norelease
        env:
          GITHUB_TOKEN: ${{ github.token }}
  validate-branch:
    name: Validate branch
    if: github.base_ref == 'main'
    runs-on: ubuntu-latest
    steps:
      - name: Only allow alpha to be merged to main
        if: github.head_ref != 'alpha'
        run: |
          echo "Only alpha should be merged to main"
          exit 1
