name: Pull Request
on:
  pull_request:
    branches:
      - main
jobs:
  validate-pr-title:
    name: Validate PR Title
    if: github.event.pull_request.draft == false
    runs-on: ubuntu-latest
    steps:
      - uses: crazy-max/ghaction-dump-context@v1
      - uses: amannn/action-semantic-pull-request@v3.4.6
        with:
          types: |
            fix
            feat
            norelease
        env:
          GITHUB_TOKEN: ${{ github.token }}
  pipeline:
    name: Build and Test with Skaffold Integration
    runs-on: ubuntu-latest
    needs:
      - validate-pr-title
    steps:
    - uses: actions/checkout@v2
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17
    - name: Install Kind
      run: |
        GO111MODULE=on go get sigs.k8s.io/kind
    - name: Install helm
      uses: azure/setup-helm@v1
      with:
        version: v3.7.1
    - name: Update helm chart dependencies
      run: |
        helm dependency update chart
    - name: Create Kind cluster
      run: |
        PATH=$(go env GOPATH)/bin:$PATH kind create cluster
    - name: Run skaffold
      uses: hiberbee/github-action-skaffold@1.12.0
      with:
        skaffold-version: 1.34.0
        command: run
    - name: Run tests
      run: |
        kubectl -n skaffoldcorndogs port-forward svc/corndogs 5080 &
        go test -v ./...
