name: Upload Released Chart
on:
  release:
    types:
      - published
jobs:
  upload-chart-gar:
    runs-on: ubuntu-latest
    steps:
      - name: Dump Context
        uses: crazy-max/ghaction-dump-context@v2
      - name: Push Chart
        uses: catalystsquad/action-upload-chart-git@v1
        with:
          token: ${{ secrets.GIT_RUNNER_TOKEN }}
